---
title: "aske_rebecca_experiment4"
author: "Aske & Rebecca"
date: "7 October 2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# STYLE - experiment 4



## Prepare data

Load packages
```{r}
# packages
pacman::p_load(tidyverse,ggbeeswarm, brms, rethinking)

```

Collect data from several csv files
```{r}

# import data from the first 55 csv files
# WD
setwd("C:/Users/askes/Dropbox/Bachelor - Aske og Rebecca/Collected data/exp4_data")
fileList4 <- list.files(full.names = T, pattern =".csv")

d4 <- map_dfr(fileList4, read_csv) %>% 
  mutate(
    ID = as.numeric(ID),
    age = as.factor(age),
    gender = as.factor(gender),
    target = as.factor(target),
    competitor1 = as.factor(competitor1),
    response = as.factor(response),
    generation = as.factor(generation),
    reaction_time = reaction_time
  )


## For ID 56-60
# set WD
setwd("C:/Users/askes/Dropbox/Bachelor - Aske og Rebecca/Collected data/exp4_data/1-6")
fileList4.2 <- list.files(full.names = T, pattern =".csv")

d4.2 <- map_dfr(fileList4.2, read_csv) %>% 
  mutate(
    ID = as.numeric(ID),
    age = as.factor(age),
    gender = as.factor(gender),
    target = as.factor(target),
    competitor1 = as.factor(competitor1),
    response = as.factor(response),
    generation = as.factor(generation),
    reaction_time = reaction_time
  )

# change participant number before merging
d4.2$ID <- d4.2$ID + 55

# rbind and create csv in shared folder
d4 <- rbind(d4, d4.2)

write.csv(d4,"C:/Users/askes/Dropbox/Bachelor - Aske og Rebecca/data_analysis/Bachelor_Rebecca_Aske/exp4_collected_data.csv", row.names = FALSE)


```

Data check
```{r}
# set wd
setwd("C:/Users/askes/Dropbox/Bachelor - Aske og Rebecca/data_analysis/Bachelor_Rebecca_Aske")

# import data
d4 <- read_csv("exp4_collected_data.csv")
   
check <- d4 %>% group_by(target) %>% summarise(n())
# Pictures appear different amounts of times because of ID (56-60)

# fast ggplot
d4 %>% ggplot(aes(generation, correct)) +
  geom_smooth(method=lm,aes(group=ID, color=ID), se=F) +
  theme_classic()


```

Create crucial columns for modelling
```{r}

# Make new column 'CorrectAnswer', describing in what side the correct picture is shown (this is generated with the column Correct and the corresponding key press)
d4$correctAnswer[d4$correct == 1] <- d4$response[d4$correct==1]
d4$correctAnswer[d4$correct == 0 & d4$response == "right"] <- "left"
d4$correctAnswer[d4$correct == 0 & d4$response == "left"] <- "right"



# Change values of generation in new colum to be -1, 0 or 1.
d4$generationNumber <- as.numeric(d4$generation)
d4$generationNumber <- ifelse(d4$generationNumber == 1, -1, d4$generationNumber)
d4$generationNumber <- ifelse(d4$generationNumber == 4, 0, d4$generationNumber)
d4$generationNumber <- ifelse(d4$generationNumber == 8, 1, d4$generationNumber)



## CREATE chainGroup column - Loop through and add chain group ID
d4$chainGroup <- NA
for (i in (1:nrow(d4))){
  
  if (d4$ID[i] <= 5) {
    d4$chainGroup[i] <- 1
    
  } else if (d4$ID[i] > 5 & d4$ID[i] < 11 | d4$ID[i] == 61) {
    d4$chainGroup[i] <- 2
    
  } else if (d4$ID[i] > 10 & d4$ID[i] < 16) {
    d4$chainGroup[i] <- 3
    
  } else if (d4$ID[i] > 15 & d4$ID[i] < 21) {
    d4$chainGroup[i] <- 4
    
  } else if (d4$ID[i] > 20 & d4$ID[i] < 26) {
    d4$chainGroup[i] <- 5
    
  } else if (d4$ID[i] > 25 & d4$ID[i] < 31) {
    d4$chainGroup[i] <- 6
    
  } else if (d4$ID[i] > 30 & d4$ID[i] < 36) {
    d4$chainGroup[i] <- 7
    
  } else if (d4$ID[i] > 35 & d4$ID[i] < 41) {
    d4$chainGroup[i] <- 8
    
  } else if (d4$ID[i] > 40 & d4$ID[i] < 46) {
    d4$chainGroup[i] <- 9
    
  } else if (d4$ID[i] > 45 & d4$ID[i] < 51) {
    d4$chainGroup[i] <- 10
    
  } else if (d4$ID[i] > 50 & d4$ID[i] < 56) {
    d4$chainGroup[i] <- 11
    
  } else { # In case we add 56-61 (which had the pictures from group 1)
    d4$chainGroup[i] <- 1
  }
}




#### CREATE BIG LOOP GOING THROUGH ALL GROUPS ####

# make empty dataframe
d4.1 <- d4[0,]

# create count
count = 1

# the LOOOP
for (group in 1:length(unique(d4$chainGroup))){
  
  
  ## for each chainGroup loop through and create StimPair unique ID
  sub <- subset(d4, chainGroup == group)


  # list of unique stimuli
  stimuli <- unique(sub$target)

  # Create dataframe x with unique stimuli pairs and stimPairID's.
  x<-NULL
  x <- data.frame(matrix(unlist(combn(stimuli, 2, simplify=F)), nrow = 276, ncol = 2, byrow=T))
  x$stimPairID <- seq(nrow(x))


  # Match stimulus pairs from x with the data and add unique ID.
  sub$stimPairID <- NA
  for (i in seq(nrow(x))){ # from 1:276
  sub$stimPairID[
    (sub$competitor1 %in% x$X1[i] | sub$competitor1 %in% x$X2[i]) & 
    (sub$competitor2 %in% x$X1[i] | sub$competitor2 %in% x$X2[i])] = x$stimPairID[i]
  }
  
  
  # Add value so they all become unique across stim groups
  sub$stimPairID <- sub$stimPairID + (1000 * count)
  count <- count + 1
  
  
  # Combine with premade empty dataframe
  if (nrow(d4.1) == 0) {
    d4.1 <- sub
    } else {
        d4.1 <- rbind(d4.1, sub)}
  
}

# Make the new stim pair id as factor
d4.1$stimPairID <- as.factor(d4.1$stimPairID)

write.csv(d4.1,"C:/Users/askes/Dropbox/Bachelor - Aske og Rebecca/data_analysis/Bachelor_Rebecca_Aske/exp4_collected_data_preprocessed.csv", row.names = FALSE)


```



## Statistical modelling - Accuracy

Import data
```{r}
# Import preprocessed data
d4 <- read_csv("exp4_collected_data_preprocessed.csv") %>% mutate(
    ID = as.factor(ID),
    age = as.factor(age),
    gender = as.factor(gender),
    target = as.factor(target),
    competitor1 = as.factor(competitor1),
    response = as.factor(response),
    generation = as.factor(generation),
    reaction_time = reaction_time,
    correctAnswer = as.factor(correctAnswer),
    generationNumber = as.numeric(generationNumber),
    chainGroup = as.factor(chainGroup),
    stimPairID = as.factor(stimPairID)
  )

```

Formulas and priors
```{r}

#the models
formula4.1 <- bf(response ~ 1 + correctAnswer * generationNumber + 
                   (1 + correctAnswer * generationNumber | ID) + 
                   (1 + correctAnswer | stimPairID) +
                   (1 + correctAnswer | target))

formula4.2 <- bf(response ~ 1 + correctAnswer * (generationNumber + I(generationNumber)^2) +
                   (1 + correctAnswer * (generationNumber + I(generationNumber)^2) | ID) + 
                   (1 + correctAnswer | stimPairID) +
                   (1 + correctAnswer | target))

# Define priors
get_prior(formula4.1, d4, family = bernoulli())

# Priors from RF
prior4.1 <- c(
           prior(normal(0,0.3), class = Intercept),
           prior(normal(0,0.3), class = b),
           prior(normal(0,0.3), class = sd),
           prior(lkj(5), class=cor))

```

Linear model 4.1
```{r}

### linear MODEL 4.1
m4.1_prior <- brm(
   formula4.1,
   data = d4,
   family = bernoulli(),
   prior = prior4.1,
   sample_prior = "only"
)

# prior predictive check
pp_check(m4.1_prior, nsamples=100)

## Better pp_check
y_pred1 <- posterior_linpred(m4.1_prior)  
dens(inv_logit(y_pred1))

# Run model
m4.1 <- brm(
   formula4.1,
   data = d4,
   family = bernoulli(),
   prior = prior4.1,
   sample_prior = TRUE
)

# add loo
m4.1 <- add_criterion(m4.1, criterion = c("bayes_R2", "loo"))

# prior predictive check
pp_check(m4.1, nsamples=100)

## Better pp_check
y_pred1 <- posterior_linpred(m4.1)  
dens(inv_logit(y_pred1))

summary(m4.1)

```

Quadratic model 4.2
```{r}

### Quadratic MODEL 4.2
m4.2_prior <- brm(
   formula4.2,
   data = d4,
   family = bernoulli(),
   prior = prior4.1,
   sample_prior = "only",
   chains = 1,
   iter = 200,
   warmup = 100
)

# prior predictive check
pp_check(m4.2_prior, nsamples=100)

## Better pp_check
y_pred1 <- posterior_linpred(m4.2_prior)  
dens(inv_logit(y_pred1))

# Run model
m4.2 <- brm(
   formula4.2,
   data = d4,
   family = bernoulli(),
   prior = prior4.1,
   sample_prior = TRUE
)

# add loo
m4.2 <- add_criterion(m4.2, criterion = c("bayes_R2", "loo"))

# prior predictive check
pp_check(m4.2, nsamples=100)

## Better pp_check
y_pred1 <- posterior_linpred(m4.2)  
dens(inv_logit(y_pred1))

summary(m4.2)

```

Control analyses without problematic pictures (4.3 and 4.4)
```{r}

# list of problematic stimuli (subjectively selected by Aske)
problemPics <- c("i3_c104_g8_id16", "i3_c104_g4_id12", "i3_c104_g1_id9",
                 "i4_c102_g4_id15", "i4_c102_g8_id315", "i4_c102_g1_",
                 "i4_c108_g4_id48", "i4_c108_g8_id52", "i4_c108_g1_id45",
                 "i3_c103_g8_id8", "i3_c103_g4_id4", "i3_c103_g1_id1")

d4sub <- subset(d4, !target %in% problemPics & !competitor1 %in% problemPics & !competitor2 %in% problemPics)



# update the 4 first models (those we will look at)
m4.3 <- update(m4.1, newdata = d4sub)
m4.4 <- update(m4.2, newdata = d4sub)

m4.3 <- add_criterion(m4.3, criterion = c("bayes_R2", "loo"))
m4.4 <- add_criterion(m4.4, criterion = c("bayes_R2", "loo"))

levels(d4sub$response)

```

Model comparisons
```{r}

# models run on all data
exp4_compare1 <- loo_compare(m4.1, m4.2) 
exp4_weights1 <- loo_model_weights(m4.1, m4.2)

# models controlling for bad pictures
exp4_compare2 <- loo_compare(m4.3, m4.4) 
exp4_weights2 <- loo_model_weights(m4.3, m4.4)

exp4_compare1
exp4_weights1
exp4_compare2
exp4_weights2

```

Results
```{r}

summary(m4.3)

hypothesis(m4.3, "")

conditional_effects(m4.3)

```


# We try a new model 
```{r}

d4 %>% group_by(correctAnswer, generationNumber) %>% summarise(
  n()
)

#the models
formula4.3 <- bf(correct ~ 1 + generationNumber + 
                   
                   (1 + generationNumber | ID) + 
                   (1 | stimPairID) +
                   (1 | target))

formula4.4 <- bf(correct ~ 1 + generationNumber + I(generationNumber)^2 +
                   
                   (1 + generationNumber + I(generationNumber)^2 | ID) + 
                   (1 | stimPairID) +
                   (1 | target))



# Define priors

# Priors from RF
prior4.2 <- c(
           prior(normal(0,1.5), class = Intercept),
           prior(normal(0,0.5), class = b),
           prior(normal(0,0.3), class = sd),
           prior(lkj(5), class=cor))





# Run LINEAR model
m4.5 <- brm(
   formula4.3,
   data = d4sub,
   family = bernoulli(),
   prior = prior4.2,
   sample_prior = TRUE
)

# add loo
m4.5 <- add_criterion(m4.5, criterion = c("bayes_R2", "loo"))

summary(m4.5)


# Run QUADRATIC model
m4.6 <- brm(
   formula4.4,
   data = d4sub,
   family = bernoulli(),
   prior = prior4.2,
   sample_prior = TRUE
)

# add loo
m4.6 <- add_criterion(m4.6, criterion = c("bayes_R2", "loo"))

summary(m4.5)
plot(hypothesis(m4.5, "generationNumber > 0"))
plot(hypothesis(m4.5, "generationNumber < 0"))

plot(m4.5)


# models run on all data
exp4_compareX <- loo_compare(m4.5, m4.6) 
exp4_weightsX <- loo_model_weights(m4.5, m4.6)

exp4_compareX
exp4_weightsX

## transforming results
#absolute effect, take base rate into account
inv_logit(0.08)
inv_logit(0.08 - 0.08)
inv_logit(0.08 - 0.08) - inv_logit(0.08) # A positive unit change in the predictor elicits a 11.5% increase in probability of choosing the left stimulus

```









## Plot
```{r}

library(pacman)
p_load(extrafont)

font_import(pattern="[T/t]imes")
loadfonts(device="win")


# Create summary dataset for visualisation
d4$correct <- as.numeric(as.character(d4$correct))

plotSum4 <- d4 %>% group_by(ID, generationNumber) %>% summarise(
  AC_Mean = mean(correct)
)

d4$generationNumber <- as.numeric(d4$generationNumber)
d4$generationNumber <- d4$generationNumber

Exp4_MainPlot <- ggplot(plotSum4, aes(generationNumber, AC_Mean)) + 
  geom_line(aes(group=ID, color=ID), alpha=0.6) +
  geom_point(aes(group=ID, color=ID), alpha=0.6) +
  geom_smooth(method=lm, color = "red") +
  scale_color_discrete(guide=FALSE) +
  scale_x_continuous(breaks = c(-1,0,1), labels=c("1st","4th", "8th")) +

  # THEMES
  theme_grey() +
  theme(
    text = element_text(family = "Times New Roman"),
    legend.position="top",
    plot.subtitle=element_text(face="italic",size=14,colour="grey40"),
    plot.title=element_text(size=21,face="bold")) +
  labs(title="\nExperiment 4",
       subtitle="Style",
       x=expression("Generation"),
       y=expression("Acurracy Rate")) +
  NULL
  
Exp4_MainPlot

```


